#pragma once

#define VIAL_KEYBOARD_UID {0xE1, 0xF6, 0x21, 0x1D, 0x64, 0x34, 0x79, 0xDB}
#define VIAL_UNLOCK_COMBO_COLS { 0, 0 }
#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }

// #define RGBLIGHT_EFFECT_KNIGHT
// #define RGBLIGHT_EFFECT_BREATHING
// #define RGBLIGHT_EFFECT_SNAKE