VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = no

LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
SPACE_CADET_ENABLE = no
WPM_ENABLE = yes

QMK_SETTINGS = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

UNICODE_ENABLE   = no  # Unicode
SWAP_HANDS_ENABLE= no  # Allow swapping hands of keyboard
EXTRAFLAGS += -flto

GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes