VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes

LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
WPM_ENABLE = yes

QMK_SETTINGS = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
